LIBSB = unix,str,dynlink,nums
PROPERERRS = -warn-error,+4+8+9+11+12+25+28
FLAGS = $(PROPERERRS),-annot,-ccopt,-fopenmp 
OBB_FLAGS = -I $(LIBSB) -cflags $(FLAGS) -lflags $(FLAGS) -lexflag -q -yaccflag -v  
all:
	ocamlc -annot -c globals.ml 
	ocamlc -annot -c gen.ml 
	ocamlc -annot -c debug.ml 
	ocamlc  -annot -I dynlink.cma nums.cma str.cma unix.cma globals.cmo gen.cmo debug.cmo lab3.ml -o lab3.exe



